services:
  service-dev:
    container_name: dev-service
    build:
      context: .
      dockerfile: ./dockerfiles/service
    environment:
      DB_HOST: mariadb
      DB_NAME: authshare
      DB_USER: authshare
      DB_PASSWORD: 5ES2#7PhHZplRm
      DENO_ENV: development
    volumes:
      - ./service:/app
    ports:
      - "8000:8000"
    command:
      ["deno", "run", "--watch", "--allow-net", "--allow-env", "./src/main.ts"]

  web-dev:
    container_name: dev-web
    build:
      context: .
      dockerfile: ./dockerfiles/web
    environment:
      DENO_ENV: development
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    command:
      ["deno", "run", "--watch", "--allow-net", "--allow-env", "./src/main.ts"]

  mariadb:
    container_name: database
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: xy9#wAX*MFQ1#Q
      MYSQL_DATABASE: authshare
      MYSQL_USER: authshare
      MYSQL_PASSWORD: 5ES2#7PhHZplRm
    volumes:
      # SQL files present in this directory will initialise the DB if it is empty on container start
      - ./sql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    ports:
      - "13006:3306"
volumes:
  db:
    name: "auth-share_db"
