services:

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: xy9#wAX*MFQ1#Q
      MYSQL_DATABASE: authshare
      MYSQL_USER: authshare
      MYSQL_PASSWORD: 5ES2#7PhHZplRm
    volumes:
      # SQL files present in this directory will initialise the DB if it is empty on container start
      - ./sql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    ports:
      - "13006:3306"
volumes:
  db:
    name: "auth-share_db"
