@startuml

class User{

    username: string
    credentials: UserCredentials
    -owned: List<Service>
    callable: List<Service>
    ownedGroups: List<Groups>
    
    +listOwnedServices(): List<Service>
    {static}authenticate(Param1..or Credential_obj): User
    
    listServices(): List<Service>
    changeUserCredentials(:UserCredentials)

    listUsergroups(): List<Group>
    listUsergroupInvitation(): List<Invitation>

    requestAuthorization(:Service)
}

class Invitation{

    sendername: string
    usergroupname: string

}

class Service{

    servicename: string
    credentials: ServiceCredentials
    
    {static}createService(:string, :User, :ServiceCredentials): Service
    authorized: List<User>
    users: List<User>
    groups: List<Group>
    invitations: List<Invitations>

    giveAuthorizationToUser(:User)
    sendInvitation(:Group)
    
    deleteService()
    callService()

    
}

class UserCredentials{

    username: string
    password: string
    
}

class ServiceCredentials{
    
    

}

class Group{
    groupname: string
    users: List<User>
    listServiceInvitation(): List<Invitation>

    {static}createUsergroup(:groupname, ): Group
    sendInvitation(:User)
    addServiceInvitation(:Invitation)
}

@enduml