@startuml Klassendiagramm

entity User{

    -credentials: UserCredentials
    -username: string
    # id: string
    -callableService: List<AllowedUserServiceMap>
    -userGroupInvitations: List<Invitation>
    -joinedGroups: List<AllowedUserGroupMap>
    -_sessions: List<Session>
    
    +listOwnedServices(): List<Service>
    {static}authenticate(Param1..or Credential_obj): User
    addInvitation(:Invitation)
    listServices(): List<Service>
    changeUserCredentials(:UserCredentials)
    
    listOwnedGroups(): List<Group>
    listUsergroups(): List<Group>
    listUsergroupInvitation(): List<Invitation>
    validateSession(sessionToken: string): Void
    findSessionByToken(sessionToken: string): Session
    deleteSessionByToken(token: string): Void
    deleteSession(session: Session): Void



    requestAuthorization(:Service)
}

struct Invitation <<ValueObject>>{

    +sendername: string
    +usergroupname: string

}

entity Service{

    servicename: string
    credentials: ServiceCredentials
    
    {static}createService(:string, :User, :ServiceCredentials): Service
    authorized: List<User>
    users: List<User>
    groups: List<Group>
    invitations: List<Invitation>

    giveAuthorizationToUser(:User)
    sendInvitation(:Group)
    
    deleteService()
    callService()

    
}

struct UserCredentials <<ValueObject>>{

    +username: string
    +hash: string
    +salt: string
    
}

struct ServiceCredentials <<ValueObject>>{
    
    -username?: string
    -password?: string
    -token?: string

}

entity Group {
    groupname: string
    users: List<User>
    sentUserInvitations: List<Invitation>
    listServiceInvitation(): List<Invitation>

    {static}createUsergroup(:groupname, ): Group
    sendInvitation(:User)
    addServiceInvitation(:Invitation)
}

struct Session <<ValueObject>>{
  +id: string
  +expiresAt: Date
  +userId: string
  
  +create(sessionToken: string, userId: string): Session
  +toString(): string
  +generateRandomSessionToken(): string
  +readonly REFRESH_INTERVAL_MS: number
  +readonly MAX_DURATION_MS: number
  +readonly fromSessionTokenToSessionId(sessionToken: string): string
}

class Entity {
  +sentInvitations: Invitation[]
  
  +getDisplayName(): string
  +getId(): string
  +convertToShort(): IdNameMap
  
  -readonly id: string
  -readonly displayname: string
  
  <<constructor>>
  Entity(id: string, displayname: string)
}


abstract class ValueClass<T extends ValueClass<T>> {
  [key: string]:
    | string
    | number
    | bigint
    | symbol
    | undefined
    | RecursiveValueClass
    | ((...args: never[]) => unknown)
    | boolean
  
  +equals(that: T): boolean
  +toString(): string
  +copy(): T
  +with(newData: Partial<OnlyProperties<T>>): T
  
  <<constructor>>
  ValueClass()
}


@enduml